# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
#standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
     {id: 7, size: 0.09},
     {id: 222, size: 0.036},
     {id: 0, size: 0.08},
     {id: 25, size: 0.033},
     {id: 24, size: 0.033},
     {id: 1, size: 0.033}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     
#   ]
tag_bundles:
 [
#   {
#      name: 'my_bundle',
#      layout:
#        [
#          {id: 7, size: 0.03, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
#          {id: 1, size: 0.03, x: 0.0994, y: 0.0877, z: 0.0517, qw: 0.7001, qx: 0.0766, qy: -0.1152, qz: 0.7005},
#          {id: 25, size: 0.03, x: -0.1044, y: 0.0945, z: 0.0296, qw: 0.0009, qx: -0.0747, qy: -0.1185, qz: 0.9901},
#          {id: 24, size: 0.03, x: 0.0950, y: -0.1062, z: -0.0015, qw: 0.7008, qx: -0.2708, qy: -0.0445, qz: 0.6585},
#          {id: 0, size: 0.03, x: -0.1054, y: -0.0963, z: -0.0429, qw: 0.6940, qx: -0.0108, qy: -0.0513, qz: -0.7181}
#        ]
#    }
  ]
